### PR TITLE
Adds spatial detection to numenta detector

### PR DESCRIPTION
**Pull request by scottpurdy**
The functional changes are in `nab/numenta/numenta_detector.py`. The updated results and threshold were generated with:

```
python run.py --detect --optimize --score --normalize -d numenta -n 8
```

There was no change to the nupic and nupic.core SHAs used.

The scoreboard in the README was updated to reflect the new results.

@subutai and @oxtopus please review

### CODE REVIEW

**Comment by oxtopus** [comment]
LGTM, but you should be prepared to update https://github.com/numenta/nupic.regression/blob/master/tests/anomaly/nab/benchmark_results.json in response to merge of this

**Comment by smirmik** [comment]
OMG!!! 😄

**Comment by smirmik** [comment]
@scottpurdy  you have two tables with results in README

**Comment by scottpurdy** [comment]
@smirmik - ahh good catch!

**Comment by scottpurdy** [comment]
Replacing with #284

**Pull request closed without merging**
