### PR TITLE
Convert NAB to Python 3

### PR DESCRIPTION
**Pull request by iandanforth**
- Like the previous PR this updates NAB to Python 3
 - NuPIC dependent detectors remain in their respective /detectors/ directories with Python 2 support code.
 - The `twitterADVec` detector instructions now has its own directory rather than living in the wiki.

Some documentation polish and final testing remains as well as removing relevant pages from the Wiki to reflect these changes.

### CODE REVIEW

**Comment by breznak** [comment]
@iandanforth PR to your branch https://github.com/iandanforth/NAB/pull/9 should fix #346 , please review and integrate here before merging

**Comment by rhyolight** [comment]
I have not reviewed this yet. I am waiting for some new hardware. But @breznak I want to be clear that we are not making NAB python 2/3 compatible. It will only be a Python 3 project.

**Comment by breznak** [comment]
> I want to be clear that we are not making NAB python 2/3 compatible. It will only be a Python 3 project. 

sorry to say that blunt, but do you have a HTM implementation to run there? As that should imho be a priority compared to py2/3 "purity"

**Comment by rhyolight** [comment]
There are other detectors that already do not run within the NAB runtime. They are run in other non-python environments and integrated into the NAB scoreboard. We are going to start treating NuPIC in Python 2.7 in the same way.

**Comment by rhyolight** [comment]
I am running every detector now. So far, so good.

**Comment by rhyolight** [comment]
I used this `Dockerfile` to run the Numenta / HTM.Java detectors:

```
FROM numenta/nupic

# Plus Java so we can run HTM.Java as well

RUN wget https://d3pxv6yz143wms.cloudfront.net/8.212.04.2/java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb && \
    apt-get update &&  apt-get install java-common && apt-get install -y --no-install-recommends apt-utils && \
    dpkg --install java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto
ENV PATH $JAVA_HOME/bin:$PATH

ENV NAB /usr/local/src/nab

ADD . $NAB

# Run Numenta detectors
RUN echo "Running numenta detectors in Python 2.7..."
WORKDIR $NAB/nab/detectors/numenta
RUN pip install -r requirements.txt
RUN python run.py --skipConfirmation

# Run HTM.Java detector
RUN echo "Running HTM.Java detector in Java 8 / Python 2.7..."
WORKDIR $NAB/nab/detectors/htmjava/nab/detectors/htmjava
RUN ./gradlew clean build
WORKDIR $NAB/nab/detectors/htmjava
RUN python run.py --skipConfirmation
```

It worked with one change. I had to `chmod a+x nab/detectors/htmjava/nab/detectors/htmjava/gradlew`. @iandanforth what do you think about making this one small change?

**Comment by rhyolight** [comment]
Ok, there was one problem running `htmjava`:

```
16: Beginning detection with htmjava for realAWSCloudwatch/ec2_cpu_utilization_fe7f93.csv
. . . . . . . . .
Running detection step
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    main(args)
  File "run.py", line 67, in main
    runner.detect({'htmjava': HtmjavaDetector})
  File "/usr/local/src/nab/nab/detectors/htmjava/nab/runner.py", line 120, in detect
    self.pool.map_async(detectDataSet, args).get(99999999)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: could not convert string to float:
The command '/bin/sh -c python run.py --skipConfirmation' returned a non-zero code: 1
```

Any ideas why this is happening?

**Comment by breznak** [comment]
> I had to make one change. I had to chmod a+x nab/detectors/htmjava/nab/detectors/htmjava/gradlew. @iandanforth what do you think about making this one small change?

I think that is fine, actually in community NAB I've removed the file and use the system provided `gradlew` (may add it as dependency)

**Comment by iandanforth** [comment]
@rhyolight I was unable to reproduce the conversion error, however I've had trouble with that particular call with that very large value. I had reduced it elsewhere but not for that line. I've done so now. 

Could you try the updated code? If it still doesn't work could you give me a bit more detail on your environment and setup?

**Comment by rhyolight** [comment]
@iandanforth I am still getting the same error. My environment is described in the [Dockerfile above](https://github.com/numenta/NAB/pull/341#issuecomment-519674341).

**Comment by rhyolight** [comment]
Continuing in #353

**Pull request closed without merging**
