### PR TITLE
Normalization cleanup

### PR DESCRIPTION
**Pull request by BoltzmannBrain**

### CODE REVIEW

**Comment by subutai** [comment]
Don't we also need to change the checked in results/baseline directory?

**Comment by BoltzmannBrain** [comment]
not yet ready for review

**Comment by subutai** [comment]
:smile:

**Comment by BoltzmannBrain** [comment]
@subutai let's wait until the new data labels are merged in so we can run the null detector and get new results files. Then those results files can be included in this PR.

**Comment by BoltzmannBrain** [comment]
@subutai should be good to go now

**Comment by subutai** [comment]
:+1:

**Pull request merged**
