### PR TITLE
Added more customizable data and results visualizing tools using Jupyter notebook

### PR DESCRIPTION
**Pull request by pasindubawantha**
- Added
  - `scripts/Plot Data.ipynb` 
  - `scripts/Plot Result.ipynb`
these files are template files that can be used to plot data and results from `/data` folder and `/results` folder using [jupyter notebook](https://jupyter.org/) and [plotly offline](https://plot.ly/python/offline/)
- Added instructions on how to plot data and results in `scripts/README.md`
- modified `.gitignore` to ignore temporary files created by Jupyter notebook

### CODE REVIEW

**Comment by rhyolight** [comment]
Thanks for the contribution. Hope you don't mind if I get to this next week.

**Comment by rhyolight** [comment]
Also @pasindubawantha, you'll need to sign our [contributor license agreement](https://numenta.org/licenses/contrib/) before we can merge.

**Comment by pasindubawantha** [comment]
Sure, thank you. Wish you a merry Christmas and a happy new year 🎊😀

**Comment by pasindubawantha** [comment]
Signed the [contributor license agreement](https://numenta.org/licenses/contrib/), thank you. Have a nice day.

**Comment by pasindubawantha** [comment]
Hello, much appreciated if this pull request can be reviewed

**Comment by rhyolight** [comment]
I am merging this change, but since it is just a utility upgrade, will not bump any versions.

**Pull request merged**
