### PR TITLE
 fixes #271, rename scoreboard algorithim

### LINKED ISSUE #271: Rename "windowed Gaussian" / "sliding threshold"
The detector is named "sliding threshold" in the scoreboard, but in the code it's "windowed Gaussian". This is confusing, we should have one name.

FWIW the algorithm is a windowed Gaussian, which is one implementation of the sliding threshold method.

### PR DESCRIPTION
**Pull request by go-bears**
changed algorithm name in README.md from 'Sliding Threshold' to 'Windowed Gaussian'

### CODE REVIEW

**Comment by go-bears** [comment]
I've already [signed the CLA](https://github.com/numenta/numenta.org/blob/gh-pages/resources/contributors.csv#L169)

**Comment by go-bears** [comment]
@rhyolight hmm, I'm still not sure what I can do to help with getting the contributor validator test to pass?

**Comment by rhyolight** [comment]
It probably has to do with the dash in your name. I'll fix it.

**Comment by rhyolight** [comment]
Making a new comment here, because it triggers a re-validation of this PR, which will dump to the logs, which I am tailing :).

**Comment by rhyolight** [comment]
I see the bug. The logs generated by this comment should help me fix it. Also, I'm glad to be abandoning the http://github.com/numenta/nupic.tools codebase. It was poorly designed (by me).

**Comment by rhyolight** [comment]
I had to add more logging. 🙄

**Comment by rhyolight** [comment]
I bet after this comment, this PR will be approved.

**Comment by rhyolight** [comment]
I bet after this comment, this PR will be approved.

**Comment by rhyolight** [comment]
@oxtopus LGTM

**Comment by go-bears** [comment]
Thanks so much for the help with this PR @rhyolight !!

**Pull request merged**
