### PR TITLE
Scoreboard formatting

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
@subutai

### CODE REVIEW

**Comment by subutai** [comment]
👍

**Comment by zuhaagha** [comment]
@BoltzmannBrain Maybe we can get rid of the version in the Additional Scoreboard too then

**Comment by BoltzmannBrain** [comment]
Thanks @zuhaagha, done.

**Comment by zuhaagha** [comment]
👍 Also, I just noticed that @subutai's changes in the additional scoreboard from [PR#246] (https://github.com/numenta/NAB/pull/246) have disappeared.

**Comment by BoltzmannBrain** [comment]
Odd, not sure how that happened. Good eye @zuhaagha, thanks, all fixed now.

**Pull request merged**
