### PR TITLE
fixes #276 updates numetaTM scores

### LINKED ISSUE #276: The numentaTM scores should be updated
The README shows the numentaTM scores as:

**reward_low_FP_rate**: 52.4
**reward_low_FN_rate**: 66.1 
**standard**: 61.2

It says this is from nupic.core SHA c030b84 (from May).

Since then, we've made a few changes to the TM:
- Bugfix: https://github.com/numenta/nupic.core/issues/1021
- Algorithm change: https://github.com/numenta/nupic.core/issues/1058
- (Lots of other changes that cause us to hit the random number generator in a different order)

And we've also fixed some bugs in the SP.

With the latest nupic.core, the numentaTM NAB scores are:

```
Final score for 'numentaTM' detector on 'reward_low_FP_rate' profile = 48.54
Final score for 'numentaTM' detector on 'reward_low_FN_rate' profile = 61.64
Final score for 'numentaTM' detector on 'standard' profile = 56.46
```

This is with optimized thresholds:

```
    "numentaTM": {
        "reward_low_FN_rate": {
            "score": -17.502002889624777,
            "threshold": 0.4942352294921876
        },
        "reward_low_FP_rate": {
            "score": -3.397888337960609,
            "threshold": 0.5126953125
        },
        "standard": {
            "score": 14.993857128859759,
            "threshold": 0.5126953125
        }
    },
```

(This drop in scores is not due to any recent change. When we made the algorithm change mentioned above, the scores were already roughly this low.)

### PR DESCRIPTION
**Pull request by go-bears**
fixes #276 
update NAB readme with latest nupic scores

### CODE REVIEW

**Comment by go-bears** [comment]
I've signed the CLA before sometime last year. Do I have to do it again?

**Comment by go-bears** [comment]
@rhyolight I resigned the CLA. How would I try to pass the contributor validator test again? Thanks so much for any info.

**Comment by rhyolight** [comment]
@go-bears No, [you are already processed](https://github.com/numenta/numenta.org/blob/gh-pages/resources/contributors.csv#L169). I'm not sure why the validator is failing. This PR is good to merge, and @cbaranski there is no need to re-process the license.

**Comment by rhyolight** [comment]
@mrcslws can you comment on this? We've been talking about this, and I think we decided we might need to do a bit more work to update the scores?

**Comment by scottpurdy** [comment]
See #287 that includes updated results as well.

**Pull request closed without merging**
