### PR TITLE
Corrected window for realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_Netwo…

### PR DESCRIPTION
**Pull request by markNZed**
I'm replacing a previous pull request with this because I've moved the fix to a branch. Here is the text from the previous PR https://github.com/numenta/NAB/pull/388 

The data file realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv has two anomalies and 1243 samples. The total amount of window length is 124 samples, so 62 for each anomaly, 31 samples prior to each anomaly and 31 samples after each anomaly.

The labels/combined_windows.json file is not correct for the first anomaly at timestamp "2013-10-10 09:35:00" or line 208 in realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv

The samples are at every 5 minutes, 31 samples prior is 2hours 35mins or timestamp "2013-10-10 07:00:00" (line 177), 31 samples after is "2013-10-10 12:10:00" (line 239)

The file labels/combined_windows.json has been updated.

This does not impact the inputs to the detectors, nor the outputs of the detectors, therefore I think this change should be included in the current NAB release. It would require rerunning the scoring (not the detectors).

### CODE REVIEW

**Comment by markNZed** [comment]
@lscheinkman thanks for looking into this (and thanks for reviewing ARTime too!). Do you think the scores table should be recalculated based on the new label window? I think this should only require rerunning the scoring step but I did not do that in this PR.

**Comment by lscheinkman** [comment]
@markNZed Thank you for pointing that out, however the label window values were not merged into NAB. The results you reported in the scores table are based on the [original label window](https://github.com/numenta/NAB/blob/master/labels/combined_windows.json#L168-L169).

This PR was closed because https://github.com/numenta/NAB/pull/393 was merged and included this commit fa5fe2c. The label window changes were reverted back to their original values in this commit 450b949 so there is no need to rerun the scoring step.

**Comment by markNZed** [comment]
@lscheinkman what happens with the bug in the original label window? I imagine that should be fixed at some point in the future.

**Comment by lscheinkman** [comment]
You can leave issue #385 open so others are aware.

Changes to the label window may require another version of NAB, but as @subutai mentioned in #386, "_NAB is in maintenance mode right now, so we can't really create a new version ..._".

**Pull request merged**
